Repository ciphertrace/apis, pull requests merged in 2022-09, with the labels that each got.

#20 Add Bran Sorem to OWNER_ALIASES for approvals
  OWNERS_ALIASES
Labels: lgtm, sig/apis, ok-to-test, size/XS, approved

#19 refactor(node): use async await in fn main
  traveler/examples/node/lookup.js
Labels: size/S, lgtm, sig/apis, ok-to-test, approved

#21 Add Rob Aagaard to owners
  OWNERS_ALIASES
Labels: lgtm, sig/apis, size/XS, approved

#22 TRV-355: node add transfer function
  .gitignore
  traveler/examples/node/lookup.js
  traveler/examples/node/package.json
  traveler/examples/node/transfer.js
Labels: size/L, lgtm, sig/apis, approved

#23 Added example code for Go development against a traveler instance
  traveler/examples/README.md
  traveler/examples/go/connection.go
  traveler/examples/go/generate.go
  traveler/examples/go/go.mod
  traveler/examples/go/go.sum
  traveler/examples/go/main.go
  traveler/examples/go/oauth.go
  traveler/examples/go/pb/.gitignore
  traveler/examples/go/pb/README.md
  traveler/examples/lookup.json
  traveler/examples/transfer.json
Labels: lgtm, sig/apis, size/XL, approved

#25 Bump Bazel to 5.3.1 and update WORKSPACE dependencies
  .bazelversion
  WORKSPACE
Labels: size/S, lgtm, sig/apis, approved

#26 Update Node example to use same JSON files as Go
  traveler/examples/node/lookup.js
  traveler/examples/node/package-lock.json
  traveler/examples/node/package.json
  traveler/examples/node/transfer.js
Labels: lgtm, sig/apis, size/XL, approved, sig/examples
