Repository ciphertrace/apis, pull requests merged in 2022-04, with the labels that each got.

#17 Bumping Bazel to 5.1.0 LTS
  .bazelversion
  WORKSPACE
Labels: size/S, lgtm, sig/apis, approved

#14 Trv 167b
  traveler/common/v1/address.proto
Labels: lgtm, sig/apis, ok-to-test, size/XS, approved

#15 Trv 188
  trisacrypto/trisa/api/v1beta1/api.proto
  trisacrypto/trisa/data/generic/v1beta1/transaction.proto
Labels: size/L, lgtm, sig/apis, ok-to-test, approved

#16 Trv 224
  traveler/common/v1/sunrise.proto
  traveler/v1/api.proto
Labels: lgtm, sig/apis, ok-to-test, size/M, approved
